### ISSUE TITLE
Add tests for generated swagger.json

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#131]
Lets add tests to swagger.json:

1. Create a simple provider with all three kinds of procedures (entity, kind, provider) with input/output models.
2. Test that swagger.json emits proper fields for all CRUD info on that kind 
   - Also make sure to test the structure of the input/output of each
3. Test that swagger.json emits proper fields for all Procedures

**Comment by shlomi-nx** [comment]
Also make sure to add a test case that checks that no extra arguments are required, as in this ticket #133

**Comment by shlomi-nx** [comment]
@Emulebest Please take a look, see whats missing. If nothing you can close.

**Comment by Emulebest** [comment]
resolved via #177
