### ISSUE TITLE
Cant invoke procedures with no arg/ret type

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#151]
```typescript
new_kind.entity_procedure('foo', {}, proc_strategy,{},{},
  (ctx: IntentfulCtx_Interface, entity: Entity, input: any) => {
    console.log('invoking..', input)
  })
```

When trying to invoke this function, we get:
`Error: Unable to execute handler 'Cannot read property 'spec' of undefined'` from here:
https://github.com/nutanix/papiea-js/blob/9b8031da0fe826c4961c6d52027e776e947dc7cc/papiea-sdk/src/provider_sdk/typescript_sdk.ts#L162-L172

**Comment by Emulebest** [comment]
This is not a bug, entity procedures expect a return type to have some notion of spec. We could add a check for that or notify user that it is required, or add a validation rule for that 
```
const result = await handler(new ProceduralCtx(this.provider_url, this.entity_url, prefix, version), {
                    metadata: req.body.metadata,
                    spec: req.body.spec,
                    status: req.body.status
                }, req.body.input);
                this.validator.validate(result.spec, Maybe.fromValue(Object.values(output_desc)[0]), Validator.build_schemas(input_desc, output_desc));
                res.json(result.spec);
```

**Comment by shlomi-nx** [comment]
A Procedure's return type should have nothing to do with a spec. I am not sure why that is the case. It could return anything, including nothing at all. 

Why is that required?
