### ISSUE TITLE
Improve schema validation error messages

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#165]
Currently, validation simply returns true/false. In case of false, it is instrumental for users to be able to easily understand the reason for the validation failure. 

Validation may fail due to the following reasons:
1. Required fields is missing
2. Unspecified field exists
3. Value of specified field is of the wrong type

We should have an informative message for each of the cases above.

**Comment by Emulebest** [comment]
Take a look at PR #176. The errors on it look quite understandable from the standpoint of a user

**Comment by Emulebest** [comment]
If you are getting error 400 from server, take a look at `e.response.errors`, it contains array of errors that occurred while validating entity

**Comment by shlomi-nx** [comment]
We should document all possible return codes and where to look for what. I did not know about this array for example and we need to make sure our users know each error code.

**Comment by Emulebest** [comment]
https://docs.google.com/document/d/1e2HbrVGTFg9TXt6ZljLM5lD9_MU5wakT5hBvoE7jLeA/edit

**Comment by Emulebest** [comment]
closed via https://github.com/nutanix/papiea-js/commit/0dd59f84df19e0c2e05a1fc0bb5c2a62b46a7926
