### ISSUE TITLE
Unable to validate a model with a type: string, expected: number

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#169]
When validating objects that were transmitted over network (such as procedure return values), numeric fields turn into strings and the validator complains.

This should behave differently. If the validator gets a string instead of a number, it should attempt to convert it and correct the structure. Only if the string cannot be converted to a number (contains illegitimate characters) it should complain.

To see this problem, look at the logs when running the following test case:
https://github.com/nutanix/papiea-js/blob/9d39cbded2e3b7fd48810b019dd3bade06d824ea/papiea-engine/__tests__/provider_sdk.test.ts#L465-L483

**Comment by Emulebest** [comment]
It seems that the test case above works.
Moreover, I believe that it might be a mistake to transform `string` to `int` if `string` could potentially be converted to `int` for example. It sounds like we are trying implicit type conversions which would make validation system have black magic inside of it

**Comment by shlomi-nx** [comment]
The tests works, obviously, but look at what it prints. 

However, the state right now is inconsistent. Some times your type is a string (if its over network), other times its a number. This is not right. We should think of this "validator" more as a coercer, where if the value validates properly, it is also always in the right type. 

What should the typescript type be for an entity with a `number` field? `string`? `number`? `string|number`? this seems wrong to me, and most other languages dont even have a `string|number` type (for futher sdks). 

I still think that a field that should be a `number` by the schema needs to be converted to a `number` type.

**Comment by shlomi-nx** [comment]
Put on hold, need to find a way to reproduce this.

**Comment by shlomi-nx** [comment]
Can't reproduce, closing
