### ISSUE TITLE
Papiea should not allow unpriviliedged users to invoke apis through api-docs

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#183]

**Comment by adolgarev** [comment]
@litvaOo I believe this is the case at the moment. BUT we should add a possibility to specify Authorization in swagger docs

**Comment by shlomi-nx** [comment]
I can create and list entities without logging in from latest master:
![Screen Shot 2019-06-24 at 12 50 22 PM](https://user-images.githubusercontent.com/39283673/60047567-da0f6b00-967e-11e9-935a-0ed3de7c70c1.png)

**Comment by adolgarev** [comment]
@shlomi-nx do not forget to set the model and policy.
Before policy is set
![Screenshot_20190625_152300](https://user-images.githubusercontent.com/323333/60098230-b1aa6e00-975d-11e9-8512-b326fca2a328.png)
Set the policy

```
export provider=tmStvTVZggA8
export admin_s2s_key=foshoh2A

curl -X POST -H 'Authorization: Bearer '${admin_s2s_key} -H "Content-Type: application/json" --data-binary '{
  "policy": "p, reader_group, anyone, geolocation, read, allow\ng2, reader_group, default",
  "authModel": "[request_definition]\nr = sub, obj, act\n[policy_definition]\np = sub, owner, obj, act, eft\n[role_definition]\ng = _, _\ng2 = _, _\n[policy_effect]\ne = some(where (p.eft == allow)) && !some(where (p.eft == deny))\n[matchers]\nm = (r.sub.owner == p.sub || g(r.sub.owner, p.sub) || g2(p.sub, 'default')) && ((p.owner == 'owner' && r.sub.owner == r.obj.metadata.extension.owner) || (p.owner == 'tenant' && r.sub.tenant == r.obj.metadata.extension.tenant_uuid) || p.owner == 'anyone' ) && (p.obj == r.obj.metadata.kind || p.obj == '*') && (r.act == p.act || p.act == '*')"
}' http://127.0.0.1:3333/provider/${provider}/0.1.0/auth
```

After policy is set
![Screenshot_20190625_152429](https://user-images.githubusercontent.com/323333/60098244-ba02a900-975d-11e9-9ba2-5f12466cbf23.png)

With proper Authorization
![Screenshot_20190625_152456](https://user-images.githubusercontent.com/323333/60098303-da326800-975d-11e9-9687-003ba5a4119d.png)
