### ISSUE TITLE
Returning a failed response from a procedure does not validate.

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#205]
a failed response currently has the structure 
```
{
  "code": integer,
  "message": string
}
```
It should be an allowed response.

**Comment by adolgarev** [comment]
change code to String type

**Comment by shlomi-nx** [comment]
@Emulebest Any progress here? Please link PR properly.

**Comment by Emulebest** [comment]
No progress here ATM

**Comment by Emulebest** [comment]
@shlomi-nx this might be related to #251

**Comment by shlomi-nx** [comment]
@Emulebest Since #251 is closed, do we need to close this as well?

**Comment by shlomi-nx** [comment]
@Emulebest Please link the lines which closes this

**Comment by shlomi-nx** [comment]
@Emulebest Is this done? If so please close

**Comment by Emulebest** [comment]
https://github.com/nutanix/papiea-js/blob/02b55976223a06a6167be7408d63302598c5fd46/papiea-engine/src/errors/papiea_error_impl.ts#L9 fixes this
