### ISSUE TITLE
procedure return validation happens in both the provider and papiea

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#206]
This in itself is not a problem, but if one passes and the other does not - that is the problem.

Please look at how can procedures have different signatures on provider and papiea sides. One passes validation one does not

**Comment by shlomi-nx** [comment]
@Emulebest Is there any progress here?

**Comment by Emulebest** [comment]
In the current releases of papiea it is not to possible to have one validation pass and other doesn't asides from edge cases that are the cause of issue #180
