### ISSUE TITLE
Ensure papiea can be built using public npm repos

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#207]
Please ensure that papiea does not depend on any component that is not in the open domain.

Papiea should be able to build on any machine with public internet access.

Please have the PR for this issue remove all dependency from our internal artifactory during circle-ci testing

**Comment by Emulebest** [comment]
@shlomi-nx Haven't found any private dependencies, they might have been required in earlier version but right now they are not

**Comment by shlomi-nx** [comment]
@Emulebest Thats good. Could you make sure that cirecle-ci does not depend on our NPM_TOKEN?

**Comment by adolgarev** [comment]
@shlomi-nx checked deps, only public available are used, no dependency on NPM_TOKEN

**Comment by Emulebest** [comment]
@shlomi-nx Should we close this one?

**Comment by shlomi-nx** [comment]
@Emulebest If this is done, and circle-ci is not using our npm_token, yes please close it.
