### ISSUE TITLE
Lets fix security vulnerabilities 

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#210]
https://github.com/nutanix/papiea-js/network/alerts

![Screen Shot 2019-07-11 at 5 47 43 PM](https://user-images.githubusercontent.com/39283673/61094445-158e9100-a404-11e9-8c8e-9a681a873c4b.png)

**Comment by adolgarev** [comment]
@shlomi-nx followed instruction here https://help.github.com/en/articles/viewing-and-updating-vulnerable-dependencies-in-your-repository but do not see any alerts ![PapieaSecurity.png](https://codetreeusercontent.s3.amazonaws.com/uploads/3df999db-4c96-46bc-82a9-5ea38ace8d45/PapieaSecurity.png)
