### ISSUE TITLE
Add logging framework to papiea

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#211]
Lets use some proper logging framework that accepts logging levels and add logs to the system.

**Comment by adolgarev** [comment]
https://www.npmjs.com/package/winston as an option

**Comment by shlomi-nx** [comment]
We should use winston. We would like to also support for centralized logging (datadog). https://docs.datadoghq.com/logs/log_collection/nodejs/?tab=winston30

**Comment by adolgarev** [comment]
@litvaOo 
1) use winston
2) replace morgan with winston as second one covers express logging use case as well
3) add ability to set logging level
4) add logs to entity api, provider api, authorizer. Log what comes in, what comes out, please use proper logging level, thus inputs/outputs may be turned off
