### ISSUE TITLE
Make EXTRA_PROPS provider level configuration

### ISSUE THREAD

**Issue by Emulebest** [nutanix/papiea-js#213]

**Comment by shlomi-nx** [comment]
The configuration should be called something like `extra_properties` that could be true of false. 

It should be configurable through the provider but allowed to be override by each entity independently. @Emulebest Is there a swagger configuration for that? If there is a standard way, perhaps the description of an entity should have that. If not, we should create one, such as `x-papiea-extra-properties`.
