### ISSUE TITLE
Add tests to core/sdk/client

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#222]
Currently we only have tests on papiea-engine. We should probably add some functional tests on the various sub packages, particularly SDK and Client.

**Comment by Emulebest** [comment]
Note, that we have tests for SDK, they are just inappropriately placed in papiea-engine

**Comment by shlomi-nx** [comment]
@Emulebest Aren't you moving tests appropriately now? Please close this when done

**Comment by Emulebest** [comment]
SDK tests are in the right place, there are no Client tests though... I'll close this one and open a new ticket to write client tests
