### ISSUE TITLE
s2s key db collection should have provider_prefix, owner, is_admin, is_provider_admin in the root

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#224]
~It should only have it in the `extension` section.~

Lets have s2skey's `user_info` as similar as possible to the `user_info` retrieved by analyzing idp tokens. Lets move `provider_prefix` OUT of `user_info` into the root, as well as `owner` and `is_provider_admin` and `is_admin`.

**Comment by adolgarev** [comment]
@shlomi-nx 

> Lets have s2skey's user_info as similar as possible to the user_info retrieved by analyzing idp tokens. Lets move provider_prefix OUT of user_info into the root, as well as owner and is_provider_admin and is_admin.

user_info is an information about the user that papiea needs to make a decision of what is permitted for him to do, it contains:
* fields parsed from idp token - used in casbin model in PerProviderAuthorizer
* provider_prefix
* is_admin and is_provider_admin  - always false if user is logged in via idp, may be true only for s2s key - used in AdminAuthorizer as well as in PerProviderAuthorizer

If you want to keep ONLY fields parsed from idp token in user_info then we somehow need to pass provider_prefix, is_admin and is_provider_admin fields - all papiea auxiliary fields - to Authorizer as they are needed to make a decision. Lets discuss on the call

**Comment by adolgarev** [comment]
* remove provider_prefix from user_info
* keep is_admin, is_provider_admin
