### ISSUE TITLE
Security: ProviderSDK needs to make an auth check to papiea when executing procedures

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#227]
When the providerSdk is receiving a procedure call, it gets the `headers` from papiea (needs #225). It then needs to make a call back to papiea, to ensure that the received token is in-fact allowed to execute this function. Otherwise, some third party may be able to send commands to run procedures on providers without properly authenticating.

**Comment by Emulebest** [comment]
Let's make additional provider security check optional

**Comment by adolgarev** [comment]
@shlomi-nx please consider https://github.com/nutanix/papiea-js/issues/233#issuecomment-512893471
