### ISSUE TITLE
Pass s2s-key as `authorization` header to procedure

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#238]
A procedure may be either called using an oauth2 user token, or with a papiea s2s-key. In the first case, the token is parsed into `userInfo` and the procedure receives the headers including the original token. This way the procedure can then act on behalf of the user. 

However, in the second case, the `userInfo` that is stored with the s2s key is being propagated to the procedure, but the `authorization` part does not. 

These two cases needs to be converged in order for the logic to be similar inside the procedure implementation. This means that whether the request comes in using a regular token or an s2s key, the procedure could rely on the `headers.authorization` to exist and be used to act on behalf of the user.

**Comment by shlomi-nx** [comment]
@Emulebest This is in review, but where is the PR?

**Comment by Emulebest** [comment]
linked to #237
