### ISSUE TITLE
Swagger model needs to contain the model for Status in responses

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#252]
Please see the following image: 
![Screen Shot 2019-08-02 at 1 01 58 PM](https://user-images.githubusercontent.com/39283673/62395650-ca106400-b525-11e9-90aa-58955f625dcc.png)

Look at the **Response section**, see the status there. Its blank `{}`. 

It should actually be everything in spec plus all the items marked `x-papiea: status-only`

**Comment by Emulebest** [comment]
Oh, the response, got it
