### ISSUE TITLE
Provider does not show on its side when a procedure return value validation failed

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#272]
The client received an error such as

```
{"error":{"code":400,"errors":[{"message":"Target property 'cluster_snapshot_uuid' is not in the model"}],"message":"Procedure invocation failed."}}
```

But on the provider side nothing was printed or alerted.

What should happen when validation fails ON A RETURN VALUE:
1. The status code needs to be 500, as this is NOT a bad request, it is an internal server error, server being the provider. If validation fails on the user input, it should be 400
2. Provider logs must complain about the error, printing out the procedure name and the offending parts that did not validate properly

**Comment by Emulebest** [comment]
@shlomi-nx Can you provide some request context please, as I can't understand the flow that caused this

**Comment by shlomi-nx** [comment]
@Emulebest I cannot recollect the exact context right now. In any case, we need to flush this out, lets add test cases for all possible errors within a procedure: receive bad input, unhandled exceptions during computations, deliberate error responses, bad return values and make sure everything is handled appropriately.

**Comment by Emulebest** [comment]
@shlomi-nx Got you, will do
