### ISSUE TITLE
Support for user/tenant/role based Feature enablement

### ISSUE THREAD

**Issue by nkntnx** [nutanix/papiea-js#296]
https://docs.google.com/document/d/1TffCYFeVaGPGJ9vDY0vJekgBhhV2Y4zQZeCwnlnbf4w/edit?usp=sharing

**Comment by shlomi-nx** [comment]
This ticket is too specific. A ticket for tighter roles assignments, on procedures and on individual fields has been created https://github.com/nutanix/papiea-js/issues/370. Closing.
