### ISSUE TITLE
`on_(create|delete)` - should not receive SFS. Improve tests

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#339]
1. `on_(create|delete)` have no use of an SFS
2. The handlers are to be invoked synchronously for the user. So a `POST` on an entity would only respond when the handler is done running, either with the created object, or with the thrown error message 
2. Throwing an error inside the handler functions should not proceed with the execution
3. Should add tests for throwing errors inside these handlers

**Comment by shlomi-nx** [comment]
@Emulebest For `on_delete` and others, please see the comment in https://github.com/nutanix/nunet-ui/issues/473

**Comment by Emulebest** [comment]
Have a few comments regarding `proceed()` let's discuss those on a call
