### ISSUE TITLE
`ctx.update_status` seems to not add an entity to the watch list

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#347]
for diff resolution.

**Comment by Emulebest** [comment]
Could you please provide your test case? An intentful task is created for entity whose `x-papiea-entity` is equal to `differ`, updating status doesn't add new tasks it only moves the progress on the one created. Correct me if I am wrong

**Comment by shlomi-nx** [comment]
If an entity has no diff (all spec == status), and a provider updates the status, the entity needs to resolve the newly created diff. For that, the entity needs to enter the watch list. 

The test scenario:
1. Create a provider with a kind that has an appropriate diff-handler and a procedure
2. The procedure updates the status of a diff-able field via `ctx.update_status`
3. Create a new entity of that kind, such that spec==status, no diff
4. Invoke the procedure on that entity, producing a diff, spec != status
5. Make sure the diff-handler is getting automatically invoked to get the entity back to a resolved state (spec==status)

**Comment by Emulebest** [comment]
Got a question on this one one. We add an entity to watchlist by creating an intentful task, so we create an intentful task when `ctx.update_status` is invoked and (spec!=status). Right now the return type for `ctx.update_status` is void, do we want to change that to return a newly created task or not?

**Comment by shlomi-nx** [comment]
No, a task and the watchlist should not be connected. a task tracks spec changes and is not required for diffs to get resolved, just for users to track the progress. status changes should be added to the watchlist without generating a task.

**Comment by Emulebest** [comment]
@shlomi-nx having status changes without tasks internally backing up those raise a lot of questions for me, including how to schedule those, what to do if the call to the handler failed, what are the rules for resolving those if there are multiple status changes happening in parallel. Can we have a brief call to think about that?

**Comment by shlomiv** [comment]
Essentially, nothing should be driven by the task. The task just gives visibility to the users. Everything on status changes should be the same as on spec changes. Only differences is spec change generate a task for the user to track, and a task it's considered "done" when there are no more fields it listens on. 

Here are the notes taken over the zoom discussion:

```
1. Spec/Status change (e1) -> WL{(e1, c=undef)}
2. Spec/Status change (e1) -> WL{(e1, c=undef)}
3. Spec/Status change (e2) -> WL{e1,e2}

4. Resolver(WL): 
4.1 de1 = Diff(e1)
4.2 if de=() Remove from WL
4.3 else if c=undef c=(invoke(next_diff(de), delay=dd)

5. WL{(e1, c=url..), (e2, c=undef)}

----
Thread: (Securing diff resolver)
Randomly pick set of entities from database (not deleted), add it to watchlist


--- spec change
CreateIntentfulTask
   --- register on spec/status updates on the entity
       --- update listening fields according to change
```

**Comment by joshua-berry-ntnx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Papiea issues needed for inventory-only BMaaS](https://trello.com/c/V6gmTU73/66-address-papiea-issues-needed-for-inventory-only-bmaas)
