### ISSUE TITLE
sdk's `check_permission` should be able to get a user token

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#350]
By default it uses the user token in the headers, but it could be useful to ask about a particular user.

**Comment by Emulebest** [comment]
Sorry, didn't get the needed workflow, please elaborate

**Comment by shlomi-nx** [comment]
The `context` argument to the various handlers (intentful and procedural) has a method called `check_permission` which lets the provider check if a user could perform some operation on an entity. This function needs to be able to receive the desired user's s2s key to check against. 

The actual `check_permission` function in the engine already accept that argument, this ticket asks for the same on the sdk's implementation.
