### ISSUE TITLE
SDK does not log unhandled exceptions

### ISSUE THREAD

**Issue by joshua-berry-ntnx** [nutanix/papiea-js#358]
If an unhandled exception occurs during execution of a Papiea procedure or intent handler, a 500 error is sent back to the Papiea engine, with some (but not all?) error details included in a blob of JSON.

The unhandled exception should _also_ be logged to stderr in a human-readable format (and possibly a machine-readable format if running in production mode).

I would consider this issue to be high-priority—I've already lost a couple hours of debugging time to this, because I didn't realize the SDK-caught errors weren't being logged, and because the actual exception was getting swallowed and replaced with a generic "Error while making request" exception somewhere along the way (I still need to look into how/why the original error got swallowed).

**Comment by joshua-berry-ntnx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address Papiea issues needed for inventory-only BMaaS](https://trello.com/c/V6gmTU73/66-address-papiea-issues-needed-for-inventory-only-bmaas)

**Comment by Emulebest** [comment]
This is already resolved in a PR linked, waiting for moving logging to core

**Comment by joshua-berry-ntnx** [comment]
Closed by #363
