### ISSUE TITLE
Use proper credentials in Circle-CI to deploy to jfrom

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#70]
Right now the user configured in Circle-CI is `danylo-quantum`, it should be `papiea-ci`

**Comment by litvaOo** [comment]
Done, can be closed

**Comment by shlomi-nx** [comment]
What is the PR number?

Next time, please add `closes #{issue number}` from the relevant PR. The reason is that github connects the PR with this issue and automatically closes it when the PR is merged.

Is this closed by https://github.com/nutanix/papiea-js/pull/72?

**Comment by litvaOo** [comment]
It does not have any PR, since it is just a config on CircleCI web UI

**Comment by shlomi-nx** [comment]
Oh ok, thanks, closing.
